// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrHElnfo-o3NL96uDT90LvhYdLueiD-Vw',
    appId: '1:1014867840813:web:0f4115f0d644df84900da4',
    messagingSenderId: '1014867840813',
    projectId: 'fir-auth-6b9b6',
    authDomain: 'fir-auth-6b9b6.firebaseapp.com',
    storageBucket: 'fir-auth-6b9b6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3AoLJmd1wHlLzgQj4Dxuhl1OOo-hu2I4',
    appId: '1:1014867840813:android:d99a69f2e0e3c5a6900da4',
    messagingSenderId: '1014867840813',
    projectId: 'fir-auth-6b9b6',
    storageBucket: 'fir-auth-6b9b6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXwYm9vUhe9akwy3B-phrTIvTqxAdaOZg',
    appId: '1:1014867840813:ios:8918ebb4e49a00ae900da4',
    messagingSenderId: '1014867840813',
    projectId: 'fir-auth-6b9b6',
    storageBucket: 'fir-auth-6b9b6.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );
}
